import { clipPreviewKey } from "./clips/config"
import { sourceToAssets } from "./r2-paths"

const FILE_EXT_RE = /\.[^.]+$/

interface ClipBounds {
  endSeconds: number
  fileId: number
  startSeconds: number
}

/** Public worker URL for a clip's poster frame (generated by the render job). */
export function getClipThumbUrl(bounds: ClipBounds): string {
  return getFileUrl(clipPreviewKey(bounds, "jpg"))
}

/** Public worker URL for a clip's hover-preview GIF. */
export function getClipGifUrl(bounds: ClipBounds): string {
  return getFileUrl(clipPreviewKey(bounds, "gif"))
}

export function getFileUrl(r2Key: string): string {
  const workerUrl = process.env.NEXT_PUBLIC_WORKER_URL
  if (!workerUrl) {
    throw new Error(
      "NEXT_PUBLIC_WORKER_URL is not set. File serving requires the Cloudflare Worker."
    )
  }
  const encoded = r2Key.split("/").map(encodeURIComponent).join("/")
  return `${workerUrl}/${encoded}`
}

/**
 * In-app file page path (`/files/...`). Encodes each path SEGMENT but keeps real
 * slashes between them — never `encodeURIComponent(wholeKey)`, which turns the
 * slashes into `%2F`. Real slashes give clean, shareable URLs and avoid `%2F`,
 * which CDNs/proxies routinely reject as a path-traversal guard. The catch-all
 * `/files/[...path]` route reconstructs the r2Key by joining the segments.
 */
export function getFilePagePath(r2Key: string): string {
  return `/files/${r2Key.split("/").map(encodeURIComponent).join("/")}`
}

/**
 * Public worker URL for a static brand asset (the auth photo, logos, OG images)
 * served from the assets bucket's `static/` folder — i.e. offloaded from Next's
 * /public to the Worker + R2.
 */
export function getStaticAssetUrl(filename: string): string {
  return getFileUrl(`assets/static/${filename}`)
}

/**
 * Mark a Worker file URL for download. The browser ignores the `download`
 * attribute on cross-origin links, so we ask the Worker to send
 * `Content-Disposition: attachment` via this query param instead.
 */
export function withDownloadParam(url: string): string {
  return `${url}${url.includes("?") ? "&" : "?"}download=1`
}

function assetParts(r2Key: string): { prefix: string; stem: string } {
  const parts = sourceToAssets(r2Key).split("/")
  const filename = parts.pop() ?? ""
  const stem = filename.replace(FILE_EXT_RE, "")
  return { prefix: parts.join("/"), stem }
}

/**
 * R2 object key (not a URL) of the 720p streaming rendition. Used server-side
 * by the clip render task to clip from the bounded 720p MP4 instead of the
 * (possibly 4K/multi-GB) original — see ADR-0002.
 */
export function getStreamVideoKey(r2Key: string): string {
  const { prefix, stem } = assetParts(r2Key)
  return `${prefix}/video-stream/${stem}_720p.mp4`
}

export function getStreamingVideoUrl(r2Key: string): string {
  return getFileUrl(getStreamVideoKey(r2Key))
}

export function getHlsPlaylistUrl(r2Key: string): string {
  const { prefix, stem } = assetParts(r2Key)
  return getFileUrl(`${prefix}/video-stream/${stem}/master.m3u8`)
}

export function getVideoThumbUrl(r2Key: string): string {
  const { prefix, stem } = assetParts(r2Key)
  return getFileUrl(`${prefix}/video-thumbs/${stem}_thumb.jpg`)
}

export function getVideoGifUrl(r2Key: string): string {
  const { prefix, stem } = assetParts(r2Key)
  return getFileUrl(`${prefix}/video-previews/${stem}_preview.gif`)
}

const CARD_THUMB_VERSION = 3

export function getCardThumbUrl(r2Key: string): string {
  const parts = sourceToAssets(r2Key).split("/")
  const filename = parts.pop() ?? ""
  const prefix = parts.join("/")
  const lastDot = filename.lastIndexOf(".")
  const stem = lastDot >= 0 ? filename.slice(0, lastDot) : filename
  const ext = lastDot >= 0 ? filename.slice(lastDot + 1).toLowerCase() : ""
  const thumbName = ext ? `${stem}_${ext}_card.webp` : `${stem}_card.webp`
  return `${getFileUrl(`${prefix}/card-thumbs/${thumbName}`)}?v=${CARD_THUMB_VERSION}`
}

export function getPdfPageUrl(r2Key: string, page: number): string {
  const { prefix, stem } = assetParts(r2Key)
  const padded = String(page).padStart(3, "0")
  return getFileUrl(`${prefix}/pdf-pages/${stem}/page-${padded}.jpg`)
}

export function getFirstPdfPageUrl(r2Key: string): string {
  return getPdfPageUrl(r2Key, 1)
}
